baseURL = "http://www.rladiesbucharest.org/"
publishDir = "docs"
languageCode = "en-us"
title = "R Ladies Bucharest"
theme = "minimal"
disqusShortname = "RLadies-Bucharest" # delete this to disable disqus comments
googleAnalytics = "UA-140459061-2"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "R Ladies Bucharest"
    description = "Community Website"
    githubUsername = "RLadies-Bucharest"
    dateFormat="2020/01/02"
    accent = "#88398A"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "Markdown"]
    copyright= "2020 © All rights reserved. R Ladies Bucharest. Powered by <a href=\"https://gohugo.io\">Hugo</a> and <a href=\"https://calintat.github.io\">Minimal</a>."


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Despre"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

#[[menu.main]]
 #   url = "/project/"
  #  name = "Projects"
   # weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:bucuresti@rladies.org"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rladies-bucharest/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rladiesbuchares/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.facebook.com/RLadiesBucharest/"
    name = "facebook"
    weight = 4

[[menu.icon]]
    url = "https://www.meetup.com/rladies-bucharest/"
    name = "meetup"
    weight = 5
    