name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ steps.vars.outputs.hugo_vr }}
        extended: true

    - name: Build
      run: hugo --minify
    
   # - name: Deploy
    #  uses: peaceiris/actions-gh-pages@v3
     # if: github.ref == 'refs/heads/master'
      #with:
       #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #  publish_dir: ./docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       destination_dir: ./docs
       keep_files: true
       full_commit_message: ${{ github.event.head_commit.message }}
       
    # Step 6 - Push our generated site to our gh-pages branch
    #- name: Deploy to GitHub Pages
     # uses: peaceiris/actions-gh-pages@v3
      #env:
       #   deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         # EXTERNAL_REPOSITORY: rladies-bucharest/rladies-bucharest.github.io/website/
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
         # publish_branch: master
          #publish_dir: ./docs
      #with:
       # emptyCommits: true
       # commitMessage: ${{ github.event.head_commit.message }}        
