name: hugo publish

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ steps.vars.outputs.hugo_vr }}
        # extended: true

    # - name: Build
    #  run: hugo --minify
    - name: Build site
      run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        github_token: ${{ secret._RLADIES_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./docs
      with:
        emptyCommits: false
        commitMessage: ${{ github.event.head_commit.message }}
